export const REACT_APP_ALL_DATA_URL = "https://cute-teal-donkey-sock.cyclic.app/api/projects"
export const REACT_APP_SEND_NEW_DATA_URL = "https://cute-teal-donkey-sock.cyclic.app/api/projects/new"
export const REACT_APP_UPDATE_DATA_URL = "https://cute-teal-donkey-sock.cyclic.app/api/projects/edit/"
export const REACT_APP_DELETE_DATA_URL = "https://cute-teal-donkey-sock.cyclic.app/api/projects/delete/"
export const REACT_APP_GET_ONE_ITEM = "https://cute-teal-donkey-sock.cyclic.app/api/projects/project/"
